### ISSUE TITLE
Use of AIS navigational status names and values?

### ISSUE THREAD

**Issue by KEGustafsson** [meri-imperiumi/signalk-autostate#11]
Could this plugin be extended to use same standadized names and values as AIS navigational status?
[http://emsa.europa.eu/cise-documentation/cise-data-model-1.5.3/model/guidelines/687507181.html](url)

**Comment by bergie** [comment]
We're using the states [as defined in the Signal K specification](https://github.com/SignalK/specification/blob/master/schemas/groups/navigation.json#L644), which I assume can then be converted to their AIS equivalents (just like AIS receivers connected to Signal K do). See for example:

https://github.com/joabakk/signalk-marinetraffic-api/blob/master/index.js#L31

But yes, we're only supporting a subset of those states (based on what we have been able to devise heuristics for). We'd be very happy to receive PRs to support more states based on telemetry in Signal K.
