### ISSUE TITLE
Intermittent 'moored' status at 1 minute interval

### ISSUE THREAD

**Issue by marcobergman** [meri-imperiumi/signalk-autostate#202]
When the interval is down to 1 minute, intermittent 'mooring' status changes occur. This was repeatedly observed in a simulated environment.

I have set the interval to 1 minute and 10m, and simulate with a fixed speed, fixed heading. He sometimes skips to 'moored', and that happens after an interval of 2 minutes, while I have set the interval to 1 minute:

```
Jun 20 11:14:59 Has moved > 10m (185 meters in 1 minutes, 3.08m/s)
Jun 20 11:14:59 Set state position to 52°20′11″N 1°6′39″W

Jun 20 11:15:59 Has moved > 10m (184 meters in 1 minutes, 3.07m/s)
Jun 20 11:15:59 Set state position to 52°20′10″N 1°6′48″W

Jun 20 11:17:59 Has only moved 0 meters in 0 minutes (0.00m/s)
Jun 20 11:17:59 State has changed from sailing to moored
Jun 20 11:17:59 Set state position to 52°20′8″N 1°7′8″W

Jun 20 11:18:59 Has moved > 10m (184 meters in 1 minutes, 3.07m/s)
Jun 20 11:18:59 State has changed from moored to sailing
Jun 20 11:18:59 Set state position to 52°20′7″N 1°7′18″W

Jun 20 11:20:59 Has only moved 0 meters in 0 minutes (0.00m/s)
Jun 20 11:20:59 State has changed from sailing to moored
Jun 20 11:20:59 Set state position to 52°20′5″N 1°7′37″W

Jun 20 11:21:59 Has moved > 10m (184 meters in 1 minutes, 3.07m/s)
Jun 20 11:21:59 State has changed from moored to sailing
Jun 20 11:21:59 Set state position to 52°20′4″N 1°7′47″W

Jun 20 11:22:59 Has moved > 10m (184 meters in 1 minutes, 3.07m/s)
Jun 20 11:22:59 Set state position to 52°20′3″N 1°7′56″W

Jun 20 11:23:59 Has moved > 10m (187 meters in 1 minutes, 3.12m/s)
Jun 20 11:23:59 Set state position to 52°20′1″N 1°8′6″W
```

**Comment by bergie** [comment]
That would make sense. We only receive a position update once per minute. So if you configure the movement interval to same, there will be times when missed position update causes a fake moored.

if you really need minute-level accuracy, the fix might be to make the subscription take the interval to account and do something like subscribing with 1/10th of that timespan so we have enough position reports to work with.

**Comment by marcobergman** [comment]
I can live with a 2-minute interval. However, if a 1-minute interval is known to cause problems, I would suggest to disable the 1-minute interval to be entered. I think it's easier to receive the position update twice as often instead.
