### ISSUE TITLE
Stops at midnight

### ISSUE THREAD

**Issue by marcobergman** [meri-imperiumi/signalk-autostate#204]
When the simulation runs overnight, I can see the boat stopping and starting at midnight in signalk-logbook. I was not awake at that time, so it might also have been caused by signalk-logbook. Nevertheless, it's a false entry.

<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/17980560/248365593-33151720-ab40-4752-8f71-9d55e037125f.png" width="400px">

**Comment by bergie** [comment]
That’s weird. Was there a Signal K restart or something? Could be #9 then.

We do overnight sails frequently without this happening.

**Comment by marcobergman** [comment]
Cannot see it reoccur so closing it for now.
