### ISSUE TITLE
Add option to consider boat as motoring without moving

### ISSUE THREAD

**Issue by macjl** [meri-imperiumi/signalk-autostate#206]
Hello,

Could it be possible to provides an option to set the state of boat as motoring, when rpm > 0, even if it’s not moving ?

**Comment by bergie** [comment]
There is no state in Signal K for "engine running but not moving". However, for instance the signalk-logbook plugin records engine start and stop separately from motion-derived states. So you'll get an "Engine started" log entry, followed by "motoring" when autostate detects motion

**Comment by bergie** [comment]
There is no state in Signal K for "engine running but not moving". However, for instance the signalk-logbook plugin records engine start and stop separately from motion-derived states. So you'll get an "Engine started" log entry, followed by "motoring" when autostate detects motion

**Comment by macjl** [comment]
Thank you for your response. 
I saw I don’t have the propulsion.*.state path in SignalK. That may be why I don’t have this entries in signalk-logbook ?
I trus, do you know which plugin can populate this path ? I have propulsion.*.revolutions that have correct informations.

**Comment by macjl** [comment]
FYI, I created a rule in signalk-derived-data plugin to populate propulsion.*.state from revolutions informations. That seems to work, and I now have entries in Logbook when motor is started or stopped. 

https://github.com/SignalK/signalk-derived-data/pull/118
