### ISSUE TITLE
State change using propulsion value

### ISSUE THREAD

**Issue by davidsanner** [meri-imperiumi/signalk-autostate#208]
What I often get now when pulling into my slip, tying up, then turning off the motor a minute or two later is an alert that I'm sailing.  No big deal of course / kind of funny but thinking about fixes.  One option might be to reduce "How often to check whether vessel is under way" to 1 or 2 minutes though this could open up false false state changes when sailing in light air (w/ current). 

From my own scripts I've found predicting state from change using location, sog, hdop and other factors is not as straightforward as one might estimate (especially w/ rare gps noise triggering false movement). 

While changing state to motoring using propulsion value is fairly clear, when turning off the motor/propulsion it's not always obvious what the next state is - moored or sailing?   Not sure an easy fix but might the rate at checking when vessel is under way be more frequent when transitioning from motoring (turning motor off) than general value (1/4) or using SOG?   

It looks like StateMachine.js  should have address this issue already but doesn't seem to be working for me.  Perhaps SOG minimum should be something like < 0.2 m/s instead of === 0 or something else going on?

**Comment by bergie** [comment]
That could be it, yes. On our boat the 0kt threshold fixed the issue completely. But I could make it configurable.

https://github.com/meri-imperiumi/signalk-autostate/commit/216613826e2f5a65d537cdbca93a78569e1f9337

**Comment by davidsanner** [comment]
Configurable would be nice but might setting value to something greater than GPS SOG noise (as low as 0.3kt or 0.16m/s which would be well below likely sailing speed) also do it?  Keep it simple?
Looking through my NMEA RMC log at the time it said I was sailing the SOG was mostly 0.0kts but would occasionally flip to 0.1kts (saw 0.2kts once) and then back to 0.0kts.  Same log showed speed through water / paddle wheel holding a solid 0.0 so looks like just random GPS noise.  Thanks

**Comment by bergie** [comment]
The problem is, GPS noise varies a lot on the equipment. Our ZG100 has some smarts inside to eliminate most of it, which is likely why the 0 has worked for us. But this also means that it is a bit difficult for me to experiment with various values to find a good threshold.

I’ll have a look at what’s the best solution later this week.

**Comment by bergie** [comment]
BTW, if you would be able to supply with some NMEA logs of arriving to dock, that would make solving this easier _and_ I could make an automated test for them to ensure we also don’t break it in the future.

**Comment by bergie** [comment]
@davidsanner can you give #209 a spin before I merge and release?

**Comment by davidsanner** [comment]
@bergie Will do... not onboard but hopefully can replay my n2k data later tonight (PST).  Will test for bugs, etc.  Thx.

**Comment by davidsanner** [comment]
I was able to do some testing playing back my candump data however my engine RPM comes from a SensESP sensor which wasn't saved so RPM stayed at zero - so not a full/proper test.   However the UI performed well as did the state calculation, though delayed w/o RPM data.  The plugin-config-data looks well formed w/ new moored_threshold value.

**Comment by bergie** [comment]
Thanks!

**Comment by davidsanner** [comment]
I took my boat out today and it seemed like everything was working well... 50M out from the dock it switched to motoring.  Later motor off & it quickly switched to sailing.  Motor on back and quickly announced motoring.  Back in slip, motor off (not moving) said moored, again only a few / several seconds delay.
But a few minutes later sitting in the slip it said "sailing" ... doh!
My settings are:  4 mins, 40M, and 0.157m/s (a little over .3kts).  
Next time out I'll bump the values up and really bump up speed value to see if that helps.... will try and test w/ my old data before then.

**Comment by davidsanner** [comment]
Looking through logbook I found these value for false change to sailing while being stopped in slip:
16/02/2024, 15:08:24  -  Stopped #navigation #trip-end
16/02/2024, 15:09:00  -  Sailing #navigation        
16/02/2024, 15:11:54   -  Stopped #navigation #trip-end
Looking through more accurate values in plugin-config-data/signalk-logbook/....
All 3 entries had SOG = 0 , STW = 0 and only about 2 meters difference in lat/long.
